"""empty message

Revision ID: 4a32cafe3baa
Revises: 
Create Date: 2021-04-27 23:11:12.834617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a32cafe3baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_client', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('t_client', 'set_timestamp')
    op.add_column('t_delivery', sa.Column('item_description', sa.String(length=50), nullable=True))
    op.add_column('t_delivery', sa.Column('item_value', sa.Integer(), nullable=False))
    op.add_column('t_delivery', sa.Column('payment_method', sa.String(length=10), nullable=False))
    op.add_column('t_delivery', sa.Column('remarks', sa.Text(length=200), nullable=True))
    op.add_column('t_delivery', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('t_delivery', sa.Column('tracking_number', sa.String(length=20), nullable=True))
    op.add_column('t_delivery', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('t_delivery', 'total_amount')
    op.drop_column('t_delivery', 'set_timestamp')
    op.drop_column('t_delivery', 'is_cancelled')
    op.drop_column('t_delivery', 'is_for_pick_up')
    op.drop_column('t_delivery', 'retry')
    op.drop_column('t_delivery', 'item_name')
    op.drop_column('t_delivery', 'is_remitted')
    op.drop_column('t_delivery', 'is_delivered')
    op.drop_column('t_delivery', 'item_amount')
    op.drop_column('t_delivery', 'is_already_pick_up')
    op.drop_column('t_delivery', 'item_weight')
    op.drop_column('t_delivery', 'is_provincial')
    op.drop_column('t_delivery', 'is_in_transit')
    op.drop_column('t_delivery', 'comments')
    op.drop_column('t_delivery', 'set_user')
    op.drop_column('t_delivery', 'tracking_id')
    op.drop_column('t_delivery', 'is_cod')
    op.drop_column('t_delivery', 'is_successful')
    op.alter_column('t_delivery_logs', 'delivery_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('t_event', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.alter_column('t_event', 'delivery_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('t_recipient', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('t_recipient', 'set_timestamp')
    op.add_column('t_sender', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('t_sender', 'set_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_sender', sa.Column('set_timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('t_sender', 'updated_timestamp')
    op.add_column('t_recipient', sa.Column('set_timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('t_recipient', 'updated_timestamp')
    op.alter_column('t_event', 'delivery_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('t_event', 'updated_timestamp')
    op.alter_column('t_delivery_logs', 'delivery_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('t_delivery', sa.Column('is_successful', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('is_cod', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('tracking_id', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('t_delivery', sa.Column('set_user', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('t_delivery', sa.Column('comments', mysql.TEXT(), nullable=True))
    op.add_column('t_delivery', sa.Column('is_in_transit', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('is_provincial', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('item_weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('t_delivery', sa.Column('is_already_pick_up', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('item_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('t_delivery', sa.Column('is_delivered', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('is_remitted', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('item_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('t_delivery', sa.Column('retry', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('t_delivery', sa.Column('is_for_pick_up', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('is_cancelled', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('t_delivery', sa.Column('set_timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('t_delivery', sa.Column('total_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('t_delivery', 'updated_timestamp')
    op.drop_column('t_delivery', 'tracking_number')
    op.drop_column('t_delivery', 'total')
    op.drop_column('t_delivery', 'remarks')
    op.drop_column('t_delivery', 'payment_method')
    op.drop_column('t_delivery', 'item_value')
    op.drop_column('t_delivery', 'item_description')
    op.add_column('t_client', sa.Column('set_timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('t_client', 'updated_timestamp')
    # ### end Alembic commands ###
