"""empty message

Revision ID: ec635319a9f1
Revises: 
Create Date: 2021-05-01 13:42:22.963591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec635319a9f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_delivery', sa.Column('service_fees_payor', sa.String(length=30), nullable=False))
    op.add_column('t_delivery', sa.Column('transaction_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_delivery', 'transaction_total')
    op.drop_column('t_delivery', 'service_fees_payor')
    # ### end Alembic commands ###
