"""empty message

Revision ID: fbae69005fc7
Revises: 
Create Date: 2021-04-21 12:53:15.065263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbae69005fc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('cellphone_no', sa.String(length=13), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('landmarks', sa.String(length=50), nullable=True),
    sa.Column('set_timestamp', sa.DateTime(), nullable=True),
    sa.Column('registered_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('receipt_id', sa.String(length=30), nullable=True),
    sa.Column('is_cod', sa.String(length=1), nullable=False),
    sa.Column('is_provincial', sa.String(length=1), nullable=False),
    sa.Column('is_for_pick_up', sa.String(length=1), nullable=False),
    sa.Column('is_already_pick_up', sa.String(length=1), nullable=False),
    sa.Column('is_in_transit', sa.String(length=1), nullable=False),
    sa.Column('is_remitted', sa.String(length=1), nullable=False),
    sa.Column('is_delivered', sa.String(length=1), nullable=False),
    sa.Column('is_successful', sa.String(length=1), nullable=False),
    sa.Column('is_cancelled', sa.String(length=1), nullable=False),
    sa.Column('retry', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=5), nullable=False),
    sa.Column('item_amount', sa.Integer(), nullable=False),
    sa.Column('item_weight', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(length=200), nullable=True),
    sa.Column('set_user', sa.String(length=20), nullable=True),
    sa.Column('set_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=1), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_pickup_available', sa.String(length=1), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('set_timestamp', sa.DateTime(), nullable=True),
    sa.Column('registered_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_pickup_available', sa.String(length=1), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['t_province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=True),
    sa.Column('cellphone_no', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('landmarks', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('set_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['t_delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_sender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=True),
    sa.Column('cellphone_no', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('landmarks', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('set_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['t_delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('is_pickup_available', sa.String(length=1), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['t_city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_district')
    op.drop_table('t_sender')
    op.drop_table('t_recipient')
    op.drop_table('t_city')
    op.drop_table('t_staff')
    op.drop_table('t_province')
    op.drop_table('t_delivery_logs')
    op.drop_table('t_delivery')
    op.drop_table('t_client')
    # ### end Alembic commands ###
