from .staff import StaffRepository
from .client import ClientRepository
from .delivery import DeliveryRepository
from .delivery_status import DeliveryStatusRepository
from .sender import SenderRepository
from .recipient import RecipientRepository
from .province import ProvinceRepository
from .city import CityRepository
from .district import DistrictRepository
